const exactAliases: Record<string, string> = {
  'socials:facebook': 'ri:facebook-fill',
  'socials:github': 'ri:github-fill',
  'socials:google': 'ri:google-fill',
  'socials:instagram': 'ri:instagram-fill',
  'socials:linkedin': 'ri:linkedin-fill',
  'socials:twitter': 'ri:twitter-x-fill',
  'payments:mastercard': 'ri:bank-card-fill',
  'payments:paypal': 'ri:paypal-fill',
  'payments:visa': 'ri:bank-card-fill',
  'custom:drag-dots-fill': 'ri:draggable',
  'custom:fast-food-fill': 'ri:drinks-2-fill',
  'custom:flash-outline': 'ri:flashlight-line',
  'custom:invoice-duotone': 'ri:bill-line',
  'custom:location-fill': 'ri:map-pin-2-fill',
  'custom:menu-duotone': 'ri:menu-line',
  'custom:profile-duotone': 'ri:user-3-fill',
  'custom:send-fill': 'ri:send-plane-2-fill',
  'custom:sidebar-fold-fill': 'ri:side-bar-fill',
  'custom:sidebar-unfold-fill': 'ri:side-bar-line',
  'carbon:bicycle': 'ri:bike-fill',
  'carbon:delivery': 'ri:truck-fill',
  'carbon:rocket': 'ri:rocket-2-fill',
};

const semanticAliases: Array<[RegExp, string]> = [
  [/eye-(closed|off)|eye-closed/, 'ri:eye-off-fill'],
  [/eye|visibility/, 'ri:eye-fill'],
  [/arrow.*(back|left)|chevron-left|arrowhead-left/, 'ri:arrow-left-s-line'],
  [/arrow.*(forward|right)|chevron-right|arrowhead-right/, 'ri:arrow-right-s-line'],
  [/arrow.*up|chevron-up/, 'ri:arrow-up-s-line'],
  [/arrow.*down|chevron-down|drop-down/, 'ri:arrow-down-s-line'],
  [/chevron-sort|transfer-horizontal/, 'ri:expand-up-down-line'],
  [/home/, 'ri:home-5-fill'],
  [/location|map-pin/, 'ri:map-pin-2-fill'],
  [/cart/, 'ri:shopping-bag-3-fill'],
  [/users|team|contacts/, 'ri:group-fill'],
  [/user-plus/, 'ri:user-add-fill'],
  [/user|profile/, 'ri:user-3-fill'],
  [/shield|verified|vpn-key|lock-password/, 'ri:shield-check-fill'],
  [/pen|edit/, 'ri:edit-2-fill'],
  [/notes|notebook|file|invoice|bill|list/, 'ri:file-list-3-fill'],
  [/camera|gallery/, 'ri:camera-fill'],
  [/cloud-upload|upload|export/, 'ri:upload-cloud-2-fill'],
  [/cloud-download|download|import|archive-down/, 'ri:download-cloud-2-fill'],
  [/trash|delete/, 'ri:delete-bin-6-line'],
  [/search/, 'ri:search-line'],
  [/settings/, 'ri:settings-3-fill'],
  [/bell|notification/, 'ri:notification-3-fill'],
  [/close/, 'ri:close-line'],
  [/add|plus/, 'ri:add-line'],
  [/minus|minimize/, 'ri:subtract-line'],
  [/checkmark|check-circle|done-all/, 'ri:checkbox-circle-fill'],
  [/danger|error|forbidden|dissatisfied/, 'ri:error-warning-fill'],
  [/info/, 'ri:information-fill'],
  [/calendar/, 'ri:calendar-event-fill'],
  [/clock|time/, 'ri:time-fill'],
  [/filter/, 'ri:filter-3-fill'],
  [/menu-dots|more-horizontal/, 'ri:more-fill'],
  [/more-vertical/, 'ri:more-2-fill'],
  [/menu/, 'ri:menu-line'],
  [/restart/, 'ri:restart-line'],
  [/fullscreen|full-screen|fit-to-screen|center-to-fit|expand|collapse/, 'ri:fullscreen-line'],
  [/zoom-in/, 'ri:zoom-in-line'],
  [/zoom-out/, 'ri:zoom-out-line'],
  [/pause/, 'ri:pause-fill'],
  [/stop/, 'ri:stop-circle-fill'],
  [/play/, 'ri:play-circle-fill'],
  [/phone/, 'ri:phone-fill'],
  [/heart|like/, 'ri:heart-3-fill'],
  [/dislike/, 'ri:dislike-fill'],
  [/share|send|forward/, 'ri:share-forward-fill'],
  [/reply/, 'ri:reply-fill'],
  [/copy/, 'ri:file-copy-fill'],
  [/link|external/, 'ri:external-link-line'],
  [/quote/, 'ri:double-quotes-l'],
  [/global/, 'ri:global-line'],
  [/star|award/, 'ri:star-fill'],
  [/flag|tag/, 'ri:price-tag-3-fill'],
  [/letter|inbox/, 'ri:mail-fill'],
  [/printer/, 'ri:printer-fill'],
  [/microphone/, 'ri:mic-fill'],
  [/volume/, 'ri:volume-up-fill'],
  [/smartphone/, 'ri:smartphone-fill'],
  [/monitor|tv/, 'ri:computer-fill'],
  [/palette|color/, 'ri:palette-fill'],
  [/bluetooth/, 'ri:bluetooth-fill'],
  [/wifi/, 'ri:wifi-fill'],
  [/android/, 'ri:android-fill'],
  [/apple/, 'ri:apple-fill'],
  [/windows/, 'ri:windows-fill'],
  [/gamepad/, 'ri:gamepad-fill'],
  [/medical/, 'ri:first-aid-kit-fill'],
  [/bed/, 'ri:hotel-bed-fill'],
  [/tea-cup|cup/, 'ri:cup-fill'],
  [/bicycle/, 'ri:bike-fill'],
  [/rocket/, 'ri:rocket-2-fill'],
  [/column|rows|view-module|view-list|view-quilt/, 'ri:layout-grid-fill'],
  [/attach/, 'ri:attachment-2'],
  [/activity|chart|trending/, 'ri:line-chart-fill'],
];

export function resolveRemixIcon(icon: string): string {
  if (icon.startsWith('ri:')) return icon;
  if (exactAliases[icon]) return exactAliases[icon];

  const iconName = icon.split(':').at(-1) ?? icon;
  return semanticAliases.find(([pattern]) => pattern.test(iconName))?.[1] ?? 'ri:circle-line';
}
